{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Database Function.py",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyO6M8BmUX/myTCs0VXYmtbo",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/139or148/abc-Online-Supermarket/blob/abc-Online-Supermarket/Database%20Function.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 365
        },
        "id": "hpgTWE5sIOp3",
        "outputId": "2ee198be-5421-4584-d9e2-5528128daa72"
      },
      "source": [
        "import webbrowser\n",
        "import datetime\n",
        "import pymysql\n",
        "from flask import Flask, render_template, redirect, url_for, request\n",
        "\n",
        "\n",
        "\n",
        "#Connect to the database\n",
        "DB = pymysql.connect(\n",
        "  host = \"127.0.0.1\",\n",
        "  user = \"Manager\",\n",
        "  password = \"E79G3T07J2\",\n",
        "  database = \"abc supermarket database\"\n",
        ")\n",
        "CUR = DB.cursor() \n",
        "\n",
        "\n",
        "\n",
        "app = Flask(__name__)\n",
        "\n",
        "           \n",
        "@app.route(\"/send_job_request\", methods = ['POST'])\n",
        "def send_job_request():\n",
        "  name  = str(request.form['name'])\n",
        "  tel   = str(request.form['tel'])\n",
        "  email = str(request.form['email'])\n",
        "  job   = str(request.form['job'])\n",
        "  date  = str(datetime.datetime.now())\n",
        "  if job == \"Driver\":\n",
        "    job_id = '101'\n",
        "  elif job == \"Deliveryman\":\n",
        "    job_id = '102'\n",
        "  elif job == \"Checker\":\n",
        "    job_id = '103'\n",
        "  elif job == \"Sale Assistant (part time)\":\n",
        "    job_id = '201'\n",
        "  elif job == \"Sale Assistant (full time)\":\n",
        "    job_id = '202'\n",
        "  elif job == \"Senior Sale Assistant\":\n",
        "    job_id = '203'\n",
        "  elif job == \"Loader\":\n",
        "    job_id = '301'\n",
        "  elif job == \"Warehouseman\":\n",
        "    job_id = '302'\n",
        "  elif job == \"Production Operative\":\n",
        "    job_id = '303'\n",
        "    \n",
        "  #Send job request to database\n",
        "  CUR.execute(\"\"\"INSERT INTO job_apply (Applicant_Name, Telephone, Email, Job_Name, Job_ID, Apply_Date)\n",
        "                 VALUES ('\"\"\" + name + \"\"\"','\"\"\" + tel + \"\"\"','\"\"\" + email + \"\"\"','\"\"\" + job + \"\"\"','\"\"\" + job_id + \"\"\"','\"\"\" + date + \"\"\"')\"\"\")\n",
        "  DB.commit()\n",
        "  \n",
        "  #Once data send to database, go back to the recent html page\n",
        "  return \"\"\"<html><body>\n",
        "              <script>\n",
        "                alert('Your request has been successfully sent!');\n",
        "                window.history.back()\n",
        "              </script>\n",
        "            </body></html>\"\"\"\n",
        "\n",
        "    \n",
        "\n",
        "@app.route(\"/member_register\", methods = ['POST'])\n",
        "def member_register():\n",
        "  fname    = str(request.form['fname'])\n",
        "  lname    = str(request.form['lname'])\n",
        "  uname    = str(request.form['uname'])\n",
        "  password = str(request.form['_password']) \n",
        "  DoB      = str(request.form['DoB'])\n",
        "  Reg_Date = str(datetime.datetime.now())\n",
        "  age      = str(request.form['age'])\n",
        "  \n",
        "  if float(age) > 65:\n",
        "    Discount = '10%'\n",
        "  else:\n",
        "    Discount = '5%'\n",
        "\n",
        "  try:\n",
        "    #Send register data to database\n",
        "    CUR.execute(\"\"\"INSERT INTO member (First_Name, Last_Name, `User_Name(email)`, Password, Date_of_Birth, Register_Date, Discount)\n",
        "                     VALUES ('\"\"\" + fname + \"\"\"','\"\"\" + lname + \"\"\"','\"\"\" + uname + \"\"\"','\"\"\" + password + \"\"\"','\"\"\" + DoB + \"\"\"','\"\"\" + Reg_Date + \"\"\"','\"\"\" + Discount + \"\"\"')\"\"\")\n",
        "    DB.commit()\n",
        " \n",
        "    #Once data send to database, go back to the recent html page   \n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  alert('You have successfully register as a member!');\n",
        "                  window.history.back()\n",
        "                </script>\n",
        "              </body></html>\"\"\"\n",
        "\n",
        "  except:\n",
        "    #If error exist, it means the user has enter an existed user name\n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  alert('This user name already exists');\n",
        "                  window.history.back()\n",
        "                </script>\n",
        "              </body></html>\"\"\"\n",
        "\n",
        "\n",
        "\n",
        "@app.route(\"/send_order\", methods = ['POST'])\n",
        "def send_order():\n",
        "  CUR.execute(\"\"\"SELECT COUNT(Order_ID) FROM `order`\"\"\")\n",
        "  order_id = CUR.fetchone()\n",
        "  order_id = str(order_id).replace('(', '')\n",
        "  order_id = str(order_id).replace(')', '')\n",
        "  order_id = str(order_id).replace(',', '')\n",
        "  order_id = str(int(order_id) + 1)\n",
        "  DB.commit()\n",
        "\n",
        "  product_list   = str(request.form['product_list']).split(\",\")\n",
        "  quantity_list  = str(request.form['quantity_list']).split(\",\")\n",
        "  order_product  = \"\"\n",
        "  for a in range(len(product_list)):\n",
        "    order_product = order_product + product_list[a] + \" x\" + quantity_list[a] + \", \"\n",
        "\n",
        "  title          = str(request.form['title'])\n",
        "  nickname       = str(request.form['nickname'])\n",
        "  phone_number   = str(request.form['phone_number'])\n",
        "  address_name   = str(request.form['address_name'])\n",
        "  floor          = str(request.form['floor'])\n",
        "  flat           = str(request.form['flat'])\n",
        "  block_building = str(request.form['block_building'])\n",
        "  estate_street  = str(request.form['estate_street'])\n",
        "  district       = str(request.form['district'])\n",
        "  region         = str(request.form['region'])\n",
        "  pay_method     = str(request.form['pay_method'])\n",
        "  \n",
        "  try:\n",
        "    credit_card  = str(request.form['credit_card'])\n",
        "  except:\n",
        "    credit_card  = \"\"\n",
        "\n",
        "  product_price  = str(request.form['product_price_input'])\n",
        "  shipping_price = str(request.form['shipping_price_input'])\n",
        "  discount       = \"0%\"\n",
        "  total_price    = str(request.form['total_price_input'])\n",
        "  \n",
        "  try:\n",
        "    #Send order to database\n",
        "    CUR.execute(\"\"\"INSERT INTO `order`\n",
        "               (Order_ID, Order_Product, Title, Name, Phone_No, Address_Name, Floor, Flat ,`Block/Building`,\n",
        "                `Estate/Street`, District, Region, Payment_Method, Credit_C_Type,\n",
        "                Product_Price, Shipping_Price, Discount, Total_Price)\n",
        "                VALUES ('\"\"\" + order_id + \"\"\"','\"\"\" + order_product + \"\"\"','\"\"\" \n",
        "                + title + \"\"\"','\"\"\" + nickname + \"\"\"','\"\"\"\n",
        "                + phone_number + \"\"\"','\"\"\" + address_name + \"\"\"','\"\"\"\n",
        "                + floor + \"\"\"','\"\"\" + flat + \"\"\"','\"\"\"\n",
        "                + block_building + \"\"\"','\"\"\" + estate_street + \"\"\"','\"\"\"\n",
        "                + district + \"\"\"','\"\"\" + region + \"\"\"','\"\"\"\n",
        "                + pay_method + \"\"\"','\"\"\" + credit_card + \"\"\"','\"\"\"\n",
        "                + product_price + \"\"\"','\"\"\" + shipping_price + \"\"\"','\"\"\"\n",
        "                + discount + \"\"\"','\"\"\" + total_price + \"\"\"')\"\"\")\n",
        "    DB.commit()\n",
        "\n",
        "    #Change Product_Stock and Total_Sale data base on Product_Name in database\n",
        "    for a in range(len(product_list)):\n",
        "      product_name = product_list[a]\n",
        "      \n",
        "      CUR.execute(\"\"\"SELECT Product_Stock FROM `product` WHERE Product_Name = '\"\"\" + product_name + \"\"\"'\"\"\")\n",
        "      old_product_quantity = CUR.fetchone()\n",
        "      old_product_quantity = str(old_product_quantity).replace('(', '')\n",
        "      old_product_quantity = str(old_product_quantity).replace(')', '')\n",
        "      old_product_quantity = str(old_product_quantity).replace(',', '')\n",
        "      new_product_quantity = str(int(old_product_quantity) - int(quantity_list[a]))\n",
        "      DB.commit()\n",
        "           \n",
        "      CUR.execute(\"\"\"UPDATE product SET Product_Stock = '\"\"\" + new_product_quantity + \"\"\"' WHERE Product_Name = '\"\"\" + product_name + \"\"\"'\"\"\")\n",
        "      DB.commit()\n",
        "\n",
        "      CUR.execute(\"\"\"SELECT Product_Total_Sale FROM `product` WHERE Product_Name = '\"\"\" + product_name + \"\"\"'\"\"\")\n",
        "      old_total_sale = CUR.fetchone()\n",
        "      old_total_sale = str(old_total_sale).replace('(', '')\n",
        "      old_total_sale = str(old_total_sale).replace(')', '')\n",
        "      old_total_sale = str(old_total_sale).replace(',', '')\n",
        "      new_total_sale = str(int(old_total_sale) + int(quantity_list[a]))\n",
        "      DB.commit()\n",
        "      \n",
        "      CUR.execute(\"\"\"UPDATE product SET Product_Total_Sale = '\"\"\" + new_total_sale + \"\"\"' WHERE Product_Name = '\"\"\" + product_name + \"\"\"'\"\"\")\n",
        "      DB.commit()\n",
        "      \n",
        "    #Once data send to database, go back to the main html page\n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  //Remove all product in shopping cart once the order has sent\n",
        "                  alert(\"Your order has been successfully sent!\");\n",
        "                  window.history.go(-3);\n",
        "                </script>\n",
        "              </body></html>\"\"\"\n",
        "  \n",
        "  except:\n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  alert('Sorry, we have some problem sending your order!');\n",
        "                  window.history.go(-3);\n",
        "                </script>\n",
        "              </body></html>\"\"\"\n",
        "\n",
        "\n",
        "@app.route(\"/forget_password\", methods = ['POST'])\n",
        "def forget_password():\n",
        "  email = str(request.form['email'])\n",
        "\n",
        "  if email != \"\":\n",
        "    CUR.execute(\"\"\"SELECT `User_Name(email)` FROM member WHERE `User_Name(email)` = '\"\"\" + email + \"\"\"'\"\"\")\n",
        "    email_result = CUR.fetchone()\n",
        "    email_result = str(email_result).replace('(', '')\n",
        "    email_result = str(email_result).replace(')', '')\n",
        "    email_result = str(email_result).replace(',', '')\n",
        "    DB.commit()\n",
        "\n",
        "    if email_result != \"None\":\n",
        "      CUR.execute(\"\"\"INSERT INTO password_find(Email)\n",
        "                    VALUES('\"\"\" + email + \"\"\"')\"\"\")\n",
        "      DB.commit()\n",
        "      return \"\"\"<html><body>\n",
        "                  <script>\n",
        "                    alert(\"We will send you a email soon to let you reset your password!\")\n",
        "                    window.history.back();\n",
        "                  </script>\n",
        "                </body></html>\"\"\"\n",
        "    \n",
        "    else: #No user name found in database\n",
        "      return \"\"\"<html><body>\n",
        "                  <script>\n",
        "                    alert(\"Sorry, we cannot find this user name!\")\n",
        "                    window.history.back();\n",
        "                  </script>\n",
        "              </body></html>\"\"\"\n",
        "      \n",
        "  else: #User cancel the find password process\n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  window.history.back();\n",
        "                </script>\n",
        "              </body></html>\"\"\"\n",
        "\n",
        "  \n",
        "@app.route(\"/login\", methods = ['POST'])\n",
        "def login():\n",
        "  user_name = str(request.form['user_name'])\n",
        "  password  = str(request.form['password'])\n",
        "\n",
        "  #Check if username and password correct/match\n",
        "  CUR.execute(\"\"\"SELECT `User_Name(email)` FROM member\n",
        "                 WHERE `User_Name(email)` = '\"\"\" + user_name + \"\"\"' AND\n",
        "                 Password = '\"\"\" + password + \"\"\"'\"\"\")\n",
        "  result = CUR.fetchone()\n",
        "  result = str(result).replace('(', '')\n",
        "  result = str(result).replace(')', '')\n",
        "  result = str(result).replace(',', '') \n",
        "  DB.commit()\n",
        "  \n",
        "  #Username and password match\n",
        "  if result != \"None\":\n",
        "    #Get user last name\n",
        "    CUR.execute(\"\"\"SELECT Last_Name FROM member\n",
        "                 WHERE `User_Name(email)` = '\"\"\" + user_name + \"\"\"'\"\"\")\n",
        "    global lname\n",
        "    lname = CUR.fetchone()\n",
        "    lname = str(lname).replace('(', '')\n",
        "    lname = str(lname).replace(')', '')\n",
        "    lname = str(lname).replace(',', '') \n",
        "    DB.commit()\n",
        "    \n",
        "    replace_location = \"\"\"<!-- Login function -->\n",
        "<button class=\"login-btn\" onclick=\"document.getElementById('login_form').style.display='block'\"><h1><b>Login</b></h1></button>\n",
        "<div id=\"login_form\" class=\"modal\">\n",
        "  <form class=\"modal-content animate\" action=\"http://localhost:5000/login\" method=\"post\">\n",
        "    <div class=\"imgcontainer\">\n",
        "      <span onclick=\"document.getElementById('login_form').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n",
        "      <img src=\"Image/Background Logo/Login Logo.png\" alt=\"User\" class=\"user\">\n",
        "    </div>\n",
        "\n",
        "    <div class=\"login_container\">\n",
        "      <div class=\"label_font_size\">\n",
        "      <label><b>Username</b></label>\n",
        "        <i>\n",
        "          <input type=\"text\" placeholder=\" Enter your username\" name=\"user_name\" id=\"user_name\" autocomplete=\"off\" required>\n",
        "        </i>\n",
        "      </div>\n",
        "\n",
        "      <p class=\"label_font_size\">\n",
        "      <label><b>Password</b></label>\n",
        "        <i>\n",
        "          <input type=\"password\" placeholder=\" Enter your password\" name=\"password\" id=\"password\" required>\n",
        "        </i>\n",
        "      </p>\n",
        "\n",
        "      <p>\n",
        "        <b><input type=\"submit\" class=\"inside-login_btn\" value=\"Login\"></b>\n",
        "      </p>\n",
        "\n",
        "      <br>\n",
        "      <br>\n",
        "       \n",
        "    </div> \n",
        "\n",
        "      <div class=\"down_container\">\n",
        "        <pre style=\"line-height: 18px\">    \n",
        "       <a href=\"abc Online Supermarket - Register Page.html\" style=\"color: blue; font-size: 18px\">Sign Up</a>                                <a href=\"abc Online Supermarket - Find Password.html\" style=\"color: black; cursor: pointer; font-size: 18px\">Forget Password?</a>\n",
        "        </pre> \n",
        "        <br>      \n",
        "      </div>     \n",
        "  </form>\n",
        "</div>\"\"\"\n",
        "    replace_new_value = \"\"\"<!-- Logout function -->\n",
        "  <div>\n",
        "  <div style=\"position: absolute; top: 30px; left: 1100px; text-align: center; font-size: 30px\"><b>Welcome Back!</b>\n",
        "    <div style=\"margin-top: -10px; color: blue\"><h3><b><i>\"\"\" + lname.replace(\"'\", \"\") + \"\"\"</i></b></h3></div>\n",
        "  </div>\n",
        "\n",
        "  <form action=\"http://localhost:5000/logout\">\n",
        "     <input type=\"image\" src=\"Image/Button Logo/Logout Logo.png\" alt=\"Logout Logo\"\n",
        "     style=\"position: absolute; top: 5px; left: 1380px; width: 120px; height: 120px\">\n",
        "  </form>\n",
        "</div>\"\"\"\n",
        "    \n",
        "    html_file = open('Templates/abc Online Supermarket - Home Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Home Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Product(Fruits) Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Product(Fruits) Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Product(Snacks) Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Product(Snacks) Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Product(Drinks and Beverages) Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Product(Drinks and Beverages) Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Product(Wines) Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Product(Wines) Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Product(Cleaning Supllies, Health and Beauty) Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Product(Cleaning Supllies, Health and Beauty) Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Product(Pets) Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Product(Pets) Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()  \n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Contact Us Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Contact Us Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - About Us Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - About Us Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Jobs Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Jobs Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Register Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Register Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Help Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Help Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Help Page Information.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Help Page Information.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()  \n",
        "\n",
        "    html_file = open('Templates/abc Online Supermarket - Serach Product Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Serach Product Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close() \n",
        "\n",
        "    CUR.execute(\"\"\"SELECT Discount FROM member\n",
        "                 WHERE `User_Name(email)` = '\"\"\" + user_name + \"\"\"'\"\"\")\n",
        "    global discount\n",
        "    discount = CUR.fetchone()\n",
        "    discount = str(discount).replace('(', '')\n",
        "    discount = str(discount).replace(')', '')\n",
        "    discount = str(discount).replace(',', '') \n",
        "    DB.commit()\n",
        "\n",
        "    if discount == \"'5%'\":\n",
        "      replace_location = \"\"\"document.getElementById(\"discount\").innerHTML = \"0% OFF  (Non-member)\"\n",
        "total_price = Math.floor(total_price*1)\"\"\"\n",
        "      replace_new_value = \"\"\"document.getElementById(\"discount\").innerHTML = \"5% OFF  (Ordinary Member)\"\n",
        "total_price = Math.floor(total_price*0.95)\"\"\"\n",
        "      html_file = open('Templates/abc Online Supermarket - Information Comfirm Page.html')\n",
        "      old_content = html_file.read()\n",
        "      new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "      with open(\"Templates/abc Online Supermarket - Information Comfirm Page.html\", \"w\") as html_file:\n",
        "        html_file.write(new_content)\n",
        "      html_file.close()\n",
        "\n",
        "    elif discount == \"'10%'\":\n",
        "      replace_location = \"\"\"document.getElementById(\"discount\").innerHTML = \"0% OFF  (Non-member)\"\n",
        "total_price = Math.floor(total_price*1)\"\"\"\n",
        "      replace_new_value = \"\"\"document.getElementById(\"discount\").innerHTML = \"10% OFF  (Elder Member)\"\n",
        "total_price = Math.floor(total_price*0.9)\"\"\"\n",
        "      html_file = open('Templates/abc Online Supermarket - Information Comfirm Page.html')\n",
        "      old_content = html_file.read()\n",
        "      new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "      with open(\"Templates/abc Online Supermarket - Information Comfirm Page.html\", \"w\") as html_file:\n",
        "        html_file.write(new_content)\n",
        "      html_file.close()\n",
        "      \n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  alert(\"You have successfully login!\")\n",
        "                  window.history.back();\n",
        "                </script>\n",
        "              </body></html>\"\"\"    \n",
        "\n",
        "  #\"None\" means the username and password not match, or username doesn't exist\n",
        "  else:\n",
        "    return \"\"\"<html><body>\n",
        "                <script>\n",
        "                  alert(\"Incorrect Username or Password!\")\n",
        "                  window.history.back();\n",
        "                </script>\n",
        "              </body></html>\"\"\"\n",
        "  \n",
        "  #with open(\"Templates/abc Online Supermarket - Home Page.html\", \"w\") as html_file:\n",
        "    #html_file.write(\"yes\")  \n",
        "\n",
        "\n",
        "@app.route(\"/logout\")\n",
        "def logout():\n",
        "  replace_location = \"\"\"<!-- Logout function -->\n",
        "  <div>\n",
        "  <div style=\"position: absolute; top: 30px; left: 1100px; text-align: center; font-size: 30px\"><b>Welcome Back!</b>\n",
        "    <div style=\"margin-top: -10px; color: blue\"><h3><b><i>\"\"\" + lname.replace(\"'\", \"\") + \"\"\"</i></b></h3></div>\n",
        "  </div>\n",
        "\n",
        "  <form action=\"http://localhost:5000/logout\">\n",
        "     <input type=\"image\" src=\"Image/Button Logo/Logout Logo.png\" alt=\"Logout Logo\"\n",
        "     style=\"position: absolute; top: 5px; left: 1380px; width: 120px; height: 120px\">\n",
        "  </form>\n",
        "</div>\"\"\"\n",
        "  replace_new_value = \"\"\"<!-- Login function -->\n",
        "<button class=\"login-btn\" onclick=\"document.getElementById('login_form').style.display='block'\"><h1><b>Login</b></h1></button>\n",
        "<div id=\"login_form\" class=\"modal\">\n",
        "  <form class=\"modal-content animate\" action=\"http://localhost:5000/login\" method=\"post\">\n",
        "    <div class=\"imgcontainer\">\n",
        "      <span onclick=\"document.getElementById('login_form').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n",
        "      <img src=\"Image/Background Logo/Login Logo.png\" alt=\"User\" class=\"user\">\n",
        "    </div>\n",
        "\n",
        "    <div class=\"login_container\">\n",
        "      <div class=\"label_font_size\">\n",
        "      <label><b>Username</b></label>\n",
        "        <i>\n",
        "          <input type=\"text\" placeholder=\" Enter your username\" name=\"user_name\" id=\"user_name\" autocomplete=\"off\" required>\n",
        "        </i>\n",
        "      </div>\n",
        "\n",
        "      <p class=\"label_font_size\">\n",
        "      <label><b>Password</b></label>\n",
        "        <i>\n",
        "          <input type=\"password\" placeholder=\" Enter your password\" name=\"password\" id=\"password\" required>\n",
        "        </i>\n",
        "      </p>\n",
        "\n",
        "      <p>\n",
        "        <b><input type=\"submit\" class=\"inside-login_btn\" value=\"Login\"></b>\n",
        "      </p>\n",
        "\n",
        "      <br>\n",
        "      <br>\n",
        "       \n",
        "    </div> \n",
        "\n",
        "      <div class=\"down_container\">\n",
        "        <pre style=\"line-height: 18px\">    \n",
        "       <a href=\"abc Online Supermarket - Register Page.html\" style=\"color: blue; font-size: 18px\">Sign Up</a>                                <a href=\"abc Online Supermarket - Find Password.html\" style=\"color: black; cursor: pointer; font-size: 18px\">Forget Password?</a>\n",
        "        </pre> \n",
        "        <br>      \n",
        "      </div>     \n",
        "  </form>\n",
        "</div>\"\"\"\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Home Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Home Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Product(Fruits) Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Product(Fruits) Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Product(Snacks) Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Product(Snacks) Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Product(Drinks and Beverages) Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Product(Drinks and Beverages) Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Product(Wines) Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Product(Wines) Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Product(Cleaning Supllies, Health and Beauty) Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Product(Cleaning Supllies, Health and Beauty) Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Product(Pets) Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Product(Pets) Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()  \n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Contact Us Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Contact Us Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - About Us Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - About Us Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Jobs Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Jobs Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Register Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Register Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Help Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Help Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Help Page Information.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Help Page Information.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()  \n",
        "\n",
        "  html_file = open('Templates/abc Online Supermarket - Serach Product Page.html')\n",
        "  old_content = html_file.read()\n",
        "  new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "  with open(\"Templates/abc Online Supermarket - Serach Product Page.html\", \"w\") as html_file:\n",
        "    html_file.write(new_content)\n",
        "  html_file.close()\n",
        "\n",
        "  if discount == \"'5%'\":\n",
        "    replace_location = \"\"\"document.getElementById(\"discount\").innerHTML = \"5% OFF  (Ordinary Member)\"\n",
        "total_price = Math.floor(total_price*0.95)\"\"\"\n",
        "    replace_new_value = \"\"\"document.getElementById(\"discount\").innerHTML = \"0% OFF  (Non-member)\"\n",
        "total_price = Math.floor(total_price*1)\"\"\"\n",
        "    html_file = open('Templates/abc Online Supermarket - Information Comfirm Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Information Comfirm Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "    \n",
        "  elif discount == \"'10%'\":\n",
        "    replace_location = \"\"\"document.getElementById(\"discount\").innerHTML = \"10% OFF  (Elder Member)\"\n",
        "total_price = Math.floor(total_price*0.9)\"\"\"\n",
        "    replace_new_value = \"\"\"document.getElementById(\"discount\").innerHTML = \"0% OFF  (Non-member)\"\n",
        "total_price = Math.floor(total_price*1)\"\"\"\n",
        "    html_file = open('Templates/abc Online Supermarket - Information Comfirm Page.html')\n",
        "    old_content = html_file.read()\n",
        "    new_content = old_content.replace(replace_location, replace_new_value)  \n",
        "    with open(\"Templates/abc Online Supermarket - Information Comfirm Page.html\", \"w\") as html_file:\n",
        "      html_file.write(new_content)\n",
        "    html_file.close()\n",
        "    \n",
        "  return \"\"\"<html><body>\n",
        "              <script>\n",
        "                window.history.back();\n",
        "              </script>\n",
        "            </body></html>\"\"\"\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "if __name__=='__main__':\n",
        "  app.run()\n",
        "\n",
        "DB.close()\n",
        "#https://stackoverflow.com/questions/48251473/how-to-write-to-a-specific-position-inside-a-html-in-python  \n"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-4-7986c5525949>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mwebbrowser\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mpymysql\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mflask\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mFlask\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrender_template\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mredirect\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl_for\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'pymysql'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ]
        }
      ]
    }
  ]
}